// Configuración del tema de Tailwind (se carga justo después del CDN de Tailwind)
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-primary-fixed-variant": "#214f3c",
        "surface-variant": "#e5e2e1",
        "on-tertiary-container": "#99baa2",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed": "#022111",
        "secondary-container": "#fdd487",
        "surface-tint": "#3a6753",
        "on-error-container": "#93000a",
        "tertiary-container": "#2d4b38",
        "tertiary-fixed": "#c8ebd1",
        "on-tertiary-fixed-variant": "#2f4d3a",
        "tertiary": "#163423",
        "outline-variant": "#c0c9c2",
        "primary-fixed": "#bceed3",
        "on-surface": "#1b1c1c",
        "primary-container": "#1f4d3a",
        "primary-fixed-dim": "#a1d1b8",
        "tertiary-fixed-dim": "#adcfb6",
        "inverse-surface": "#303030",
        "on-secondary-container": "#785a19",
        "surface-bright": "#fcf9f8",
        "outline": "#717973",
        "secondary-fixed": "#ffdea4",
        "on-background": "#1b1c1c",
        "on-secondary-fixed-variant": "#5d4200",
        "on-surface-variant": "#414944",
        "secondary-fixed-dim": "#e8c176",
        "surface": "#fcf9f8",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#002114",
        "surface-container-highest": "#e5e2e1",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#261900",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "surface-dim": "#dcd9d9",
        "background": "#fcf9f8",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae7e7",
        "primary": "#023625",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "secondary": "#775a19",
        "on-primary-container": "#8dbda4",
        "inverse-primary": "#a1d1b8",
        "on-tertiary": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "space-xl": "3.5rem",
        "space-lg": "2rem",
        "margin-mobile": "1.25rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "margin": "3rem"
      },
      "fontFamily": {
        "body-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Playfair Display"],
        "body-md": ["Plus Jakarta Sans"],
        "subheading": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-xl": ["Playfair Display"],
        "headline-sm": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-md": ["Playfair Display"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-xl-mobile": ["Playfair Display"],
        "label-sm": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "subheading": ["18px", { "lineHeight": "28px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-sm": ["22px", { "lineHeight": "30px", "fontWeight": "500" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["28px", { "lineHeight": "36px", "fontWeight": "500" }],
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "headline-xl-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.12em", "fontWeight": "600" }]
      }
    }
  }
}
